# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-18 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_excel'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel', models.FileField(null=True, upload_to=b'')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='excel',
        ),
        migrations.AlterField(
            model_name='student',
            name='sap_id',
            field=models.IntegerField(default=1),
        ),
    ]
