# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-18 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160918_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s1_p',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='s2_t',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='s3_t',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='s4_t',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='s5_t',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='s6_p',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='s6_t',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='s7_l',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='s7_t',
            field=models.IntegerField(null=True),
        ),
    ]
