# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-18 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20160918_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s7_p_c',
            field=models.DecimalField(decimal_places=1, max_digits=11, null=True),
        ),
    ]
