# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-18 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20160918_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s6_p_g',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='s7_p_g',
            field=models.IntegerField(null=True),
        ),
    ]
