# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-19 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20160919_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s1_p',
            field=models.IntegerField(default=0),
        ),
    ]
