# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-19 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20160919_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s2_t',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='s3_t',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='s4_t',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='s5_t',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='s6_p',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='s6_t',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='s7_l',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='s7_t',
            field=models.IntegerField(default=0),
        ),
    ]
